spring:
  zipkin:
    base-url: http://zipkin:9411/
  sleuth: 
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://annuaire:1111/eureka/
    healthcheck:
      enabled: true
    preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: zone1
    
management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - beans
        - health
        - metrics
        - httptrace
        - refresh
        - routes
        - hystrix
        - hystrix.stream
        
  endpoint:
    health:
      show-details: always

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  hystrix:
    enabled: true    

logging:
  level:
    root: INFO
    
