version: "3.5"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    networks:
     - elk
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.1
    networks:
     - elk
    ports:
      - "25826:25826"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    networks:
     - elk
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

networks:
  elk:
